services:
  - type: web
    name: r-quisitions-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run seed && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: r-quisitions-db
          property: connectionString
      - key: NODE_ENV
        value: production
    autoDeploy: false

databases:
  - name: r-quisitions-db
    databaseName: requisitions
    user: requisitions_user
    plan: free
